### ISSUE TITLE
pi constant isn't translated

### ISSUE THREAD

**Issue by ClemtM** [ebranlard/matlab2python#10]
In Matlab, "pi" is already defined but in python it has to be replace by np.pi to work correctly

**Comment by ebranlard** [comment]
Hi @ClemtM, thanks for pointing that out. At this stage, I wouldn't know how to go about it (I'm a bit rusty on this code). 

My workaround would be to include `from numpy import pi` at the beginning of the python function... I know it doesn't really answer the issue, maybe someone else will find a better solution?

**Comment by ebranlard** [comment]
Nevermind, I believe I found a way to fix this, [5b15201]. (https://github.com/ebranlard/matlab2python/commit/5b152015f691a9e88da51559a040b56a3f022377)
