### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1

### ISSUE THREAD

**Issue by AA1999** [ebranlard/matlab2python#12]
Hey guys
I ran matlap2python on a matlab code but it seems like it gives me this exact error:

```py
Traceback (most recent call last):
  File "/home/arshia/Desktop/matlab2python/matlab2python.py", line 49, in <module>
    main(sys.argv[1:])
  File "/home/arshia/Desktop/matlab2python/matlab2python.py", line 44, in main
    mparser.matlab2python(opts.filelist,opts)
  File "/home/arshia/Desktop/matlab2python/matlabparser/parser.py", line 433, in matlab2python
    matlab2python(f,opts)
  File "/home/arshia/Desktop/matlab2python/matlabparser/parser.py", line 437, in matlab2python
    MF=MatlabFile(filename=filename)
  File "/home/arshia/Desktop/matlab2python/matlabparser/parser.py", line 185, in __init__
    self.raw_lines=f.readlines()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 242: invalid start byte
```

I will upload the matlab file to show what I mean exactly

[matlab code.zip](https://github.com/ebranlard/matlab2python/files/9154677/matlab.code.zip)

The error seems to have migrated from smop cause smop had the same exact issue

**Comment by ebranlard** [comment]
Thanks for reporting this. 
I'm using python 3.9.9 on windows, and was able to read your files without error. Does this simple read code works on your files? 
```python
with open('myfile.m','r') as f:
   raw_lines=f.readlines()
```

**Comment by AA1999** [comment]
There seems to be no error on that code.

Python info is:

```
➜  ~ python --version
Python 3.10.5
```

My operating system is Arch-Linux

**Comment by AA1999** [comment]
My bad, the other file shows no errors, however on this one I see this

```py
➜  imagefusion_Infrared_visible_latlrr git:(master) ✗ python test.py
Traceback (most recent call last):
  File "/home/arshia/Desktop/imagefusion_Infrared_visible_latlrr/test.py", line 2, in <module>
    raw_lines = f.readlines()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 242: invalid start byte
```

The file I opened was `latent_lrr.m` which I believe is included in the zip

**Comment by ebranlard** [comment]
Sounds good, I guess  the following will do the trick, no?
```python
with open('latent_lrr.m','r', errors='ignore') as f:
   raw_lines=f.readlines()
```

**Comment by AA1999** [comment]
Yeah it seems to work now
I even made sure to see If it prints the lines and it seems to do that

**Comment by ebranlard** [comment]
Sounds good, I've submitted a small correction. Encoding errors are always a bit of a pain. The alternative would be to detect the encoding using `chardet`, but hopefully this workaround is enough.

**Comment by AA1999** [comment]
I hope so too! I'll close the Issue until I see another of the same.
Tried on the codes and both worked!

Tyvm
