### ISSUE TITLE
Matlab and OpenFAST related issues

### ISSUE THREAD

**Issue by zme1213** [ebranlard/matlab2python#21]
Dear sir, l'm sorry to bother you. l'm a student from China. We are working on a project. Now their are some problems. I know you're an expert at this, so l'd like to consult with you.  OpenFAST has a dynamic link library Hydro-dynamics, which can directly call the calculation, but it is DLL. How can the dynamic link library be called in Matlab, or how can it be used in Matlab?

**Comment by ebranlard** [comment]
Hi
I'd advise to post this question on the openfast repository https://github.com/OpenFAST/openfast
