### ISSUE TITLE
Opening single quote Exception in comment line

### ISSUE THREAD

**Issue by ReimundR** [ebranlard/matlab2python#3]
Hi there, thanks for the interesting Matlab/Octave parser.

I plan to add an Matlab/Python analyser which compares the class stucture for Matlab and Python implementation to support porting from one language into another.

I'm getting now an Excpetion 'Opening single quote found, should not happen!' in extract_quotedstring() at line 162 of parsing_tools.py
for the following pure comment line in a Matlab class:
`%         * '': automatic by file extension: '.zip' or '.snap' as zip`

I could try to fix it, however I am not familiar with the code so it could be not optimal. Please let know if you would fix it.

Regards, Reimund

**Comment by ebranlard** [comment]
Thank you for pointing that out. I've pushed a quick fix. You'll notice that matlab2python has its limitation. It does save a bit of time for conversions.

**Comment by ReimundR** [comment]
Hi, thank your for the fix! Is working now.
That's fine. ;)
