### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by pberger514** [ebranlard/matlab2python#7]
Hi there,

Thanks for this project!

I have a small feature I've added for the TODO for parent objects and ampersands in Matlab. I've tested it on a pretty large Objective Matlab codebase that I'm porting and it works for all the cases I've encountered there. I have it on a feature branch which I tried to push after cloning with Github CLI but I'm getting permission denied. What's the best way for me to PR?

**Comment by ebranlard** [comment]
Hi @HaMetBacon 
Thanks for contributing. I could give you access to the repo, but maybe you can try the following, which is more the "typical" workflow:
- Fork this repository (by clicking on fork at the top)
- Clone your fork of this repository. 
- (it's good practice to create a branch, but you don't really have to)
- Commit your changes locally, and push them to your repo
- Go on your github page of the repo, github should suggest a link to create a pull request

Let me know if have issues at any point, and thanks again for contributing!

**Comment by pberger514** [comment]
Sounds good, thanks!
